name: iwm-environment
channels:
  - conda-forge
dependencies:
  - python-graphviz
  - pip:
    - "pydotplus==2.0.2"
    - "graphviz==0.20.3"
    - "ipywidgets==8.1.2"
    - "lxml==5.2.1"
    - "rdflib @ git+https://github.com/white-gecko/rdflib@a87f83fa9fc615a4fec72e9dd525d038cd5b1c02"
    - "sickle==0.7.0"
